controls = [132, 261, 1576, 2397]
display = [447, 410, 943, 861]
a = [1461, 1820, 227, 248]
b = [1164, 1956, 227, 248]
left = [142, 1816, 162, 444]
right = [455, 1816, 162, 444]
up = [162, 1788, 440, 162]
down = [162, 2116, 440, 162]
select = [542, 2377, 251, 180]
start = [843, 2377, 251, 180]
